### ISSUE TITLE
any chance you can fix boreal theme?

### ISSUE THREAD

**Issue by mohad12211** [MiniDiscordThemes/rmkx#1]
hey! I would really appreciate it if you can fix the colors for the forums.
currently its like this:
![image](https://user-images.githubusercontent.com/51754973/212480101-530a1595-0ff0-4ebe-980e-c1c1b163e352.png)
feel free to close this issue if you don't want to bother fixing it.

**Comment by Saltssaumure** [comment]
These themes are now discontinued.
